### ISSUE TITLE
LIBCLANG TOOLING ERROR

### ISSUE THREAD

**Issue by lyqssb** [Kolkir/cppminer#2]
When I try `python3 miner.py -c 1000 ../data path/to` on my ubuntu16.04,I got this error. it looks like this:
 Parallel processes num: 4
Max contexts num: 1000
Max path length: 0
Max sub-tokens num: 5
Max AST depth: 0
Input path: /home/cleowang/code2seq/cppminer/data
Output path: /home/cleowang/code2seq/cppminer/src/path/to
Parsing files ...
LIBCLANG TOOLING ERROR: fixed-compilation-database: Error while opening fixed database: No such file or directory
json-compilation-database: Error while opening JSON database: No such file or directory

LIBCLANG TOOLING ERROR: fixed-compilation-database: Error while opening fixed database: No such file or directory
json-compilation-database: Error while opening JSON database: No such file or directory

How can i fix it? thank you!

**Comment by Kolkir** [comment]
@lyqssb Hi, this message comes from `libclang` and say that you don't have a `json-compilation-database`. In general, you can simply ignore it if you don't care about compilation flags and include directories for your sources. Otherwise, just create such a file with your build system or other tools.

**Comment by lyqssb** [comment]
@Kolkir If such error dosen't influence the merge step, I'll choose to ignore it~ 
Thank you so much!
